### PR TITLE
fix(devtab): visual tweaks to the devtab

### LINKED ISSUE #1: 21.10: Partition management buttons in Gnome Disks have two round corners and two sharp corners
**Describe the problem:**
The partition remover button in Gnome Disks looks like it has a styling bug. The two left corners are sharp, but the two right corners are rounded

**Steps to reproduce:**
1. On 21.10, open Gnome disks

**Distribution:**
Pop!\_OS 21.10

**Pop version:**
```
Installed: 5.4.4~1629398560~21.10~6615e45
```
```
Pop Gtk theme - Pop Gtk theme used by System76

          ID: org.gtk.Gtk3theme.Pop-dark
         Ref: runtime/org.gtk.Gtk3theme.Pop-dark/x86_64/3.22
        Arch: x86_64
      Branch: 3.22
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1.1 MB

      Commit: cb13fccb1a397f172bbfa27e7f9b6e1b4d16b5a316768f67f3ba178e14f1ad6a
      Parent: 01db4ce9aee609219f7c47db545f445cdaa0bb9a4c6088ca3b09e9cd1e747227
     Subject: add flathub.json (6f5d1226)
        Date: 2020-11-17 21:02:13 +0000
```

### PR DESCRIPTION
**Pull request by isantop**
Tweaks the corner radii and padding to help it better flow with the grid above.

Fixes #1

### CODE REVIEW

**Comment by isantop** [comment]
Changes to the below visual appearance:

image

**Comment by isantop** [comment]
Also looks good when using Adwaita:

image

And Yaru:

image

Tested with dark versions of Pop, Adwaita, and Yaru as well.

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — CHANGES_REQUESTED** [review]
I don't think gnome-disk-utility.pot should be committed, it is auto generated. Also, this _might_ need to be a quilt patch.

**Comment by isantop** [comment]
> I don't think gnome-disk-utility.pot should be committed, it is auto generated. 

Ah, yep. I see that now. I'll get that removed and added to the gitignore to avoid future commit issues

> Also this _might_ need to be a quilt patch

I can set that up, if this won't work

**Comment by isantop** [comment]
@jackpot51 I went ahead and re-applied this as a quilt patch. We should be GTG

**Review by jackpot51 — APPROVED** [review]
Looks good!

**Comment by isantop** [comment]
I don't know why I didn't learn quilt patching earlier. It's quite pleasant.

**Pull request merged**
